# The main job for config_tests.
resources:
  jobs:
    config_tests_job:
      name: config_tests_job

      schedule:
        # Run every day at 8:37 AM
        quartz_cron_expression: '44 37 8 * * ?'
        timezone_id: Europe/Amsterdam

      email_notifications:
        on_failure:
          - dominika.makuch@thoughtworks.com

      parameters:
        - name: config_file_path
          default: ${var.config_file_path}

      tasks:
        - task_key: main_task
          job_cluster_key: job_cluster
          python_wheel_task:
            package_name: config_tests
            entry_point: main
          libraries:
            # By default we just include the .whl file generated for the config_tests package.
            # See https://docs.databricks.com/dev-tools/bundles/library-dependencies.html
            # for more information on how to add other libraries.
            - whl: ../dist/*.whl


      job_clusters:
        - job_cluster_key: job_cluster
          new_cluster:
            spark_version: 14.3.x-scala2.12
            node_type_id: Standard_D3_v2
            autoscale:
                min_workers: 1
                max_workers: 1
